name: Build and Publish front-end

on:
  push:
    branches: ["main", "test"]
  workflow_dispatch:
    inputs:
      version:
        description: "tag version. ex: 1.0.0"
        default: ""
        type: string
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 16
      - run: npm install
      - run: npm run build
      - uses: actions/upload-artifact@v4
        with:
          name: theme-artifact
          path: dist
      - name: Bump version and push tag
        if: ${{ inputs.version != '' }}
        env:
          version: v${{ inputs.version }}
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add -f dist
          git commit -am "${{ env.version }}"
          git tag -a "${{ env.version }}" -m "${{ env.version }}"
          git push origin "${{ env.version }}"
          echo "version=${{ env.version }}" >> $GITHUB_ENV
      - name: Upload Wheel as Release Asset
        uses: softprops/action-gh-release@v1
        if: ${{ inputs.version != '' && env.version != '' }}
        with:
          name: ${{ env.version }}
          tag_name: ${{ env.version }}
          files: dist/*.*
